# Difference-in-Differences

## What is Panel Data?

Panel data describes the setting in which we have repeated observations over time for the same units (e.g., people, firms, counties, etc.). Such data often present an opportunity to estimate causal effects more convincingly than in a purely cross-sectional setting, although that's certainly not always the case. I'd much rather read a strong analysis of "lesser" data than a poor analysis of "better" data. But all else equal, panel data tend to contain more information and more dimensions of variation than we see in cross-sectional data, and thus more opportunities for causal inference.

Slightly more formally, we observe some outcome $y$ for units $i=1,...,N$ and over time periods $t=1,...,T$. We denote the outcome for a given unit and time by $y_{it}$. Keeping with our potential outcomes framework and notation, let's assume that some units receive treatment at some time $t$, which we denote by the indicator $1(D_{it}=1)$. We also observe some other time-varying characteristics for each unit, denoted $W_{it}$. 


## What is Difference-in-Differences?

Difference-in-differences (DD) is an identification strategy that essentially attempts to predict the counterfactual for the treated group using the change in outcomes among the control group. Intuitively, we assume that the outcomes for those that ultimately received treatment *would have* evolved just as the outcomes for those that did not receive treatment (on average).




## Presentations
Below are some presentations I've made in different settings. These more or less repeat the information above but in a presentation format (more figures, fewer words). 

```{r echo=FALSE}
knitr::include_url("https://imccart.github.io/empirical-methods/difference-in-differences/slides/intro-cdc202108.html")
```

<a href="https://imccart.github.io/empirical-methods/panel-data/slides/did-cdc202108.html">CDC Workshop, August 2021</a>


## Code Files
What good is a discussion of data and econometrics without some practice?! Here are some very basic code files to implement the estimators described above.

- [Stata Code](code/Stata-panel.do)
- [R Code](code/R-panel.R)

- [Stata Code](code/Stata-did.do)
- [R Code](code/R-did.R)

