---
title: "Difference-in-Differences"
date: '2021-08-12'
output: 
  md_document:
    variant: markdown_github
    toc: TRUE
    toc_depth: 3
    pandoc_args: --webtex
bibliography: '../BibTeX_Library.bib'
math: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(error = TRUE, comment = NA, warnings = FALSE, errors = FALSE, messages = FALSE, tidy = FALSE, echo = FALSE)
library(googledrive)
drive_download("Bibliography/BibTeX_Library.bib", overwrite=TRUE, path='../BibTeX_Library.bib')
```

# What is Difference-in-Differences?

Difference-in-differences (DD) is an identification strategy that essentially attempts to predict the counterfactual for the treated group using the change in outcomes among the control group. Intuitively, we assume that the outcomes for those that ultimately received treatment *would have* evolved just as the outcomes for those that did not receive treatment (on average).

# Presentations
Below are some presentations I've made in different settings. These more or less repeat the information above but in a presentation format (more figures, fewer words). 

<a href="https://imccart.github.io/empirical-methods/panel-data/slides/dd-cdc202108.html">CDC Workshop, August 2021</a>


# Code Files
What good is a discussion of data and econometrics without some practice?! Here are some very basic code files to implement the estimators described above.

- [Stata Code](code/Stata-panel.do)
- [R Code](code/R-panel.R)



# References


