---
title: "TWFE and Event Studies"
date: '2021-08-12'
output: 
  md_document:
    variant: markdown_github
    toc: TRUE
    toc_depth: 3
    pandoc_args: --webtex
bibliography: '../BibTeX_Library.bib'
math: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(error = TRUE, comment = NA, warnings = FALSE, errors = FALSE, messages = FALSE, tidy = FALSE, echo = FALSE)
library(googledrive)
drive_download("Bibliography/BibTeX_Library.bib", overwrite=TRUE, path='../BibTeX_Library.bib')
```

# What is TWFE?

Two-way fixed effects (TWFE) is essentially just a shorthand for a specific and very common regression specification that includes fixed effects for units $i=1,...,N$ and time $t=1,...,T$. I'll denote these by $\gamma_{i}$ and $\gamma_{t}$, respectively. TWFE is more general than a 2x2 DD specification because it allows for intercept shifts for each units and for each time period, as opposed to shifts only among each treated/control group and treated/control period. However, this extra generality doesn't really do much in the case of a single treated group and a single treatment time, since the overall group and overall treatment period dummies in the 2x2 case are effectively an average of the individual unit and individual time period fixed effects, respectively.

More formally, recall our original DD regression specification, $$y_{it} = \alpha + \beta \times 1(Post) + \lambda \times 1(Treat) + \delta \times 1(Post) \times 1(Treat) + \varepsilon$$

# Presentations
Below are some presentations I've made in different settings. These more or less repeat the information above but in a presentation format (more figures, fewer words). 

<a href="https://imccart.github.io/empirical-methods/panel-data/slides/twfe-cdc202108.html">CDC Workshop, August 2021</a>


# Code Files
What good is a discussion of data and econometrics without some practice?! Here are some very basic code files to implement the estimators described above.

- [Stata Code](code/Stata-twfe.do)
- [R Code](code/R-twfe.R)


# References




